sudo: required

services:
     - docker 


before_install:

       - docker build -t react -f ./client/Dockerfile.dev ./client

script:
       - docker run -e CI=true react npm test


after_success:

    - docker build -t amit2328/multi-client ./client
    - docker build -t amit2328/multi-nginx ./nginx
    - docker build -t amit2328/multi-server ./server
    - docker build -t amit2328/multi-client ./client
    - docker build -t amit2328/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push amit2328/multi-client
    - docker push amit2328/multi-nginx
    - docker push amit2328/multi-server
    - docker push amit2328/multi-worker
